# Generated by Django 4.2.8 on 2023-12-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poem_collected_by_poem_collected_from_poem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
