# Generated by Django 4.2.8 on 2023-12-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_poem_image_url_poem_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='english_meaning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='english_writing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='telugu_writing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
