# Generated by Django 4.2.8 on 2023-12-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_poem_english_meaning_poem_english_writing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='telugu_meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
